------------------------------------------------------------------------------------------------
-- Name: Gavin Papenthien
-- Project: Attendance App - This is a full stack attendance tracking and management software.
-- Purpose: Create database schema for API to construct entities and interfaces with.
------------------------------------------------------------------------------------------------
CREATE TABLE roles
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE users
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    student_card_id VARCHAR(50),
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id INT REFERENCES roles(id)
);

CREATE TABLE courses
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    section_count INT NOT NULL DEFAULT 0
);

CREATE TABLE sections
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_num VARCHAR(10) NOT NULL,
    num_students INT NOT NULL DEFAULT 0,
    course_id INT REFERENCES courses(id),
    professor_id INT REFERENCES users(id)
);

CREATE TABLE meeting_times
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INT REFERENCES sections(id),
    day_of_week INT,
    start_time TIME,
    end_time TIME
);

CREATE TABLE attendance_logs
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT REFERENCES users(id),
    section_id INT REFERENCES sections(id),
    date_time TIMESTAMP,
    excused BOOLEAN,
    is_absent BOOLEAN
);

CREATE TABLE enrollments
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INT REFERENCES sections(id),
    student_id INT REFERENCES users(id)
);

INSERT INTO roles (name) VALUES
('Administrator'),
('Professor'),
('Student');
